export const CURRENCIES = {
  INR: { code: 'INR', symbol: '₹', rate: 1.0, label: 'INR' },
  USD: { code: 'USD', symbol: '$', rate: 0.012, label: 'USD' },
  EUR: { code: 'EUR', symbol: '€', rate: 0.011, label: 'EUR' },
  GBP: { code: 'GBP', symbol: '£', rate: 0.0094, label: 'GBP' },
  CAD: { code: 'CAD', symbol: '$', rate: 0.016, label: 'CAD' },
  AUD: { code: 'AUD', symbol: '$', rate: 0.018, label: 'AUD' },
  JPY: { code: 'JPY', symbol: '¥', rate: 1.88, label: 'JPY' },
};

export const PRODUCTS = [
  {
    id: 'beanie-lime',
    title: 'BEANIE',
    subtitle: 'LIME GREEN',
    image: '/imagess/greencap/greencap.webp',
    images: [
      '/imagess/greencap/greencap.webp',
      '/imagess/greencap/greencap1.webp',
    ],
    hex: '#D1F362',
    price: 4100,
    soldOut: false,
    category: 'Accessories',
    description: 'Heavy knit minimalist watch cap beanie with signature contrast energy stitching. Finished with micro raw edge detailing and standard dualfold utility cuff.',
    sizeOptions: ['ONE SIZE'],
    offsetX: '-16px',
    offsetY: '-10px',
    scale: 0.85
  },
  {
    id: 'beanie-iris',
    title: 'BEANIE',
    subtitle: 'IRIS BLUE',
    image: 'https://skylrk.com/cdn/shop/files/IMG-0760.png?v=1777665440&width=800',
    hex: '#c3bfd8',
    price: 4100,
    soldOut: true,
    category: 'Accessories',
    description: 'Premium soft brushed knit beanie with detailed contrast hemline stitching. Soft cloud comfort finish designed to stay structured under extreme cold conditions.',
    sizeOptions: ['ONE SIZE'],
    offsetX: '21px',
    offsetY: '-36px',
    scale: 0.85
  },
  {
    id: 'reverse-hoodie-iris',
    title: 'REVERSE HOODIE',
    subtitle: 'WASHED IRIS',
    image: 'https://skylrk.com/cdn/shop/files/REVERSEHOODIE_IRIS_FRONT.png?v=1777408516&width=800',
    hex: '#c3bfd8',
    price: 8200,
    soldOut: true,
    category: 'Hoodies',
    description: 'Ultra-heavy 620GSM loopback cotton custom woven fleece hoodie. Subversively garment dyed with individual color pooling, resulting in high-end vintage washed finish variations.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '-9px',
    offsetY: '17px',
    scale: 1.15
  },
  {
    id: 'reverse-hoodie-lime',
    title: 'REVERSE HOODIE',
    subtitle: 'ACID LIME',
    image: 'https://skylrk.com/cdn/shop/files/REVERSEHOODIE_LIME_FRONT.png?v=1777408327&width=800',
    hex: '#D1F362',
    price: 8200,
    soldOut: false,
    category: 'Hoodies',
    description: 'Double-layered drop shoulder reverse construction hoodie in signature neon acid hue. Featuring dual-cinch elasticated drawcords and structural rib cuffs.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '28px',
    offsetY: '-9px',
    scale: 1.15
  },
  {
    id: 'reverse-sweats-iris',
    title: 'REVERSE JOGGER',
    subtitle: 'WASHED IRIS',
    image: '/imagess/bluetrack/bluetrack.webp',
    images: [
      '/imagess/bluetrack/bluetrack.webp',
      '/imagess/bluetrack/bluetrack1.webp',
      '/imagess/bluetrack/bluetrack2.webp',
      '/imagess/bluetrack/bluetrack3.webp',
      '/imagess/bluetrack/bluetrack4.webp',
      '/imagess/bluetrack/bluetrack5.webp',
    ],
    hex: '#c3bfd8',
    price: 7200,
    soldOut: false,
    category: 'Joggers',
    description: 'Baggy-cut architectural sweatpant designed with deep raw utility side pockets. Fully elasticated dual cinch ankle closures for rapid crop adjustment on footwear.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '-2px',
    offsetY: '-35px',
    scale: 1.15
  },
  {
    id: 'reverse-sweats-lime',
    title: 'REVERSE JOGGER',
    subtitle: 'ACID LIME',
    image: 'https://skylrk.com/cdn/shop/files/REVERSEJOGGER_LIME_CINCHEDFRONT.png?v=1777409563&width=800',
    hex: '#D1F362',
    price: 7200,
    soldOut: false,
    category: 'Joggers',
    description: 'Heavyweight organic cotton loopback French terry sweats in dynamic acid lime. Styled with hidden flat drawstrings, heavy metal aglets, and structural knee darts.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '-32px',
    offsetY: '18px',
    scale: 1.15
  },
  {
    id: 'reverse-zip-hoodie-white',
    title: 'REVERSE ZIP HOODIE',
    subtitle: 'ECOLOGY CHALK',
    image: 'https://skylrk.com/cdn/shop/files/SLT026-0011-1_7d646b62-144a-42d6-bf00-b6e720eff254.png?v=1777082141&width=800',
    hex: '#FBF9F9',
    price: 8900,
    soldOut: true,
    category: 'Hoodies',
    description: 'Premium brushed cotton outerwear fitted with custom-extruded matte silver double slider zippers. Fully lined hood with structured shape-retention canvas padding.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '5px',
    offsetY: '-8px',
    scale: 1.15
  },
  {
    id: 'reverse-sweats-white',
    title: 'REVERSE SWEATS',
    subtitle: 'ECOLOGY CHALK',
    image: 'https://skylrk.com/cdn/shop/files/SLB028-0011-1_65d1f5d2-2d0b-4936-8673-ec3627544c06.png?v=1777664878&width=800',
    hex: '#FBF9F9',
    price: 6500,
    soldOut: false,
    category: 'Joggers',
    description: 'Minimalist straight-leg ecology cotton loungewear trousers. Natural custom fiber dyes bring an earthy chalk-white aesthetic paired nicely with clean footwear silhouettes.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '-25px',
    offsetY: '-34px',
    scale: 1.15
  },
  {
    id: 'slouch-sock-pack',
    title: 'SLOUCH SOCK 2-PACK',
    subtitle: 'HEATHER IRIS BRIGHT',
    image: 'https://skylrk.com/cdn/shop/files/IMG_1743-2.png?v=1778526741&width=800',
    hex: '#E8D1EB',
    price: 1800,
    soldOut: false,
    category: 'Accessories',
    description: 'Thick, breathable premium ribbed athletic slouch socks featuring supportive arch compression grids. Comes as a dual-colored pack matching current seasonal apparel dye shades.',
    sizeOptions: ['S/M', 'L/XL'],
    offsetX: '12px',
    offsetY: '19px',
    scale: 1.0
  },

  {
    id: 'rest-slide-tennis',
    title: 'REST SLIDE',
    subtitle: 'TENNIS GREEN',
    image: 'https://skylrk.com/cdn/shop/files/restslidetennis_lowered.png?v=1761252859&width=800',
    hex: '#85DC60',
    price: 4100,
    soldOut: false,
    category: 'Footwear',
    description: 'Anatomically designed active recovery slip-on in brilliant electric grass tennis green. High-traction grid layout ensures premium performance on water or dry courts.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '19px',
    offsetY: '-33px',
    scale: 1.1
  },
  {
    id: 'rest-slide-bloop',
    title: 'REST SLIDE',
    subtitle: 'BLOOP DEEP OCEAN',
    image: 'https://skylrk.com/cdn/shop/files/restslidebloop_lowered.png?v=1761252857&width=800',
    hex: '#2e4a52',
    price: 4100,
    soldOut: false,
    category: 'Footwear',
    description: 'Dark mineral navy EVA slides utilizing deep structural footcups and thick protective sole blocks. Made with marine eco-friendly composite organic polymers.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '-11px',
    offsetY: '20px',
    scale: 1.1
  },
  {
    id: 'rest-slide-sand',
    title: 'REST SLIDE',
    subtitle: 'SAHARA SAND',
    image: 'https://skylrk.com/cdn/shop/files/restslidesand_lowered.png?v=1764114219&width=800',
    hex: '#b19573',
    price: 4100,
    soldOut: false,
    category: 'Footwear',
    description: 'Earthy desaturated dune sand-colored recovery footwear. Features soft responsive landing patterns and dynamic horizontal vents to control inner micro-temperatures.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '26px',
    offsetY: '-6px',
    scale: 1.1
  },
  {
    id: 'rest-slipper-pie',
    title: 'REST SLIPPER',
    subtitle: 'PIE CHERRY RED',
    image: 'https://skylrk.com/cdn/shop/files/Rest_Slipper_Pie_Right.png?v=1776965205&width=800',
    hex: '#de463e',
    price: 4500,
    soldOut: false,
    category: 'Footwear',
    description: 'Quilted micro-ripstop puffer slippers lined in thick thermal shearling fleece. Keeps natural warmth encapsulated while retaining structural wind protection.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '-4px',
    offsetY: '-32px',
    scale: 1.1
  },
  {
    id: 'rest-slipper-fresh',
    title: 'REST SLIPPER',
    subtitle: 'FRESH CLOVER',
    image: 'https://skylrk.com/cdn/shop/files/Rest_Slipper_Fresh_Green_Right_83f738fd-5e8b-42f6-b9b6-598d38f84966.png?v=1776965214&width=800',
    hex: '#05AA3D',
    price: 4500,
    soldOut: false,
    category: 'Footwear',
    description: 'Rich leaf green organic down-filled puffy slippers. Memory-foam insoles dynamically adjust to footprint pressure over time for custom orthotic alignment.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '33px',
    offsetY: '21px',
    scale: 1.1
  },
  {
    id: 'bump-case-red',
    title: 'BUMP CASE',
    subtitle: 'JELLY CHERRY',
    image: 'https://skylrk.com/cdn/shop/files/IPHONE_17_PRO_JELLY_BACK_29667_1_jpg_64972a29-33ea-4cc4-8b5e-2cbf1a9f219b.png?v=1768581985&width=800',
    hex: '#EE4F4F',
    price: 3200,
    soldOut: false,
    category: 'Cases',
    description: 'Glossy dual-layer thermal TPU shock-absorbing case with custom raised lens protective shields. Liquid clear crystal red borders show modern device aesthetic colors.',
    sizeOptions: ['IPHONE 15 PRO', 'IPHONE 16 PRO', 'IPHONE 16 PRO MAX', 'IPHONE 17 PRO', 'IPHONE 17 PRO MAX'],
    offsetX: '3px',
    offsetY: '-5px',
    scale: 0.95
  },
  {
    id: 'bump-case-blue',
    title: 'BUMP CASE',
    subtitle: 'SUPER BARCODE BLUE',
    image: 'https://skylrk.com/cdn/shop/files/IPHONE_16_PRO_SUPER_BLUE_BACK_29687_25_jpg_798d12c7-f522-4912-927c-3949120d592e.png?v=1768582041&width=800',
    hex: '#5BBAD2',
    price: 3200,
    soldOut: false,
    category: 'Cases',
    description: 'Ultra tough shock bumper outer frame case formatted with signature cyber logo barcodes. Resistant to fingerprints and oil build-ups.',
    sizeOptions: ['IPHONE 15 PRO', 'IPHONE 16 PRO', 'IPHONE 16 PRO MAX', 'IPHONE 17 PRO', 'IPHONE 17 PRO MAX'],
    offsetX: '-27px',
    offsetY: '-31px',
    scale: 0.95
  },
  {
    id: 'bump-case-goo',
    title: 'BUMP CASE',
    subtitle: 'GOO SLIME GREEN',
    image: 'https://skylrk.com/cdn/shop/files/IPHONE_17_PRO_GOO_BACK_29674_5_jpg_4cb0ef9b-a0e6-4032-aef9-0c9c11195962.png?v=1768581991&width=800',
    hex: '#28DC73',
    price: 3200,
    soldOut: false,
    category: 'Cases',
    description: 'Liquid silicone custom finish phone case with internal protective microfiber dust sheets. Scratch proof structure ensures pristine screen guard lines.',
    sizeOptions: ['IPHONE 15 PRO', 'IPHONE 16 PRO', 'IPHONE 16 PRO MAX', 'IPHONE 17 PRO', 'IPHONE 17 PRO MAX'],
    offsetX: '10px',
    offsetY: '22px',
    scale: 0.95
  },
  {
    id: 'sizzler-case-pink',
    title: 'SIZZLER CASE',
    subtitle: 'NEO CHUBA PINK',
    image: 'https://skylrk.com/cdn/shop/files/SKYLRK_IPHONE_17_PRO_MAX_PINK_BACK_28152_jpg.png?v=1769799089&width=800',
    hex: '#FFC0CB',
    price: 3500,
    soldOut: false,
    category: 'Cases',
    description: 'Fluffy bubble style cloud puff extreme protect bumper case. Features a tactile back design that is highly satisfying to hold and doubles as a pocket-stress reliever.',
    sizeOptions: ['IPHONE 15 PRO', 'IPHONE 16 PRO', 'IPHONE 16 PRO MAX', 'IPHONE 17 PRO', 'IPHONE 17 PRO MAX'],
    offsetX: '-20px',
    offsetY: '-4px',
    scale: 1.0
  },
  {
    id: 'sizzler-case-jet',
    title: 'SIZZLER CASE',
    subtitle: 'JET BACK CARBON',
    image: 'https://skylrk.com/cdn/shop/files/SKYLRK_IPHONE_17_PRO_MAX_JET_BACK_28148_jpg_e89aa9fd-093e-4106-bf49-35bfcbd9f9ac.png?v=1775768074&width=800',
    hex: '#353433',
    price: 3500,
    soldOut: false,
    category: 'Cases',
    description: 'Puff jacket textured matte carbon phone case engineered to survive 3-meter drop metrics. Seamless integration with active magnetic chargers.',
    sizeOptions: ['IPHONE 15 PRO', 'IPHONE 16 PRO', 'IPHONE 16 PRO MAX', 'IPHONE 17 PRO', 'IPHONE 17 PRO MAX'],
    offsetX: '17px',
    offsetY: '-30px',
    scale: 1.0
  },
  {
    id: 'sunken-mule-cave',
    title: 'SUNKEN MULE',
    subtitle: 'CAVE EXTREME ORE',
    image: 'https://skylrk.com/cdn/shop/files/SKYLRK_32composite_CAVE.png?v=1774913722&width=800',
    hex: '#353433',
    price: 12000,
    soldOut: false,
    category: 'Footwear',
    description: 'Futuristic hybrid clogs cast from custom organic charcoal bio-based polyols. Deep interior vents and supportive arch curves accommodate thick athletic apparel socks.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '-6px',
    offsetY: '-29px',
    scale: 1.25
  },
  {
    id: 'sunken-mule-sand',
    title: 'SUNKEN MULE',
    subtitle: 'ALABASTER DUNE',
    image: 'https://skylrk.com/cdn/shop/files/SKYLRK_32composite_f0209fcb-8545-48ee-a0cc-c840e9568881.png?v=1774913742&width=800',
    hex: '#b48652',
    price: 12000,
    soldOut: false,
    category: 'Footwear',
    description: 'Premium light ochre custom foam mules fitted with slip-resistant active terrain outsoles. Waterproof monolithic shape ensures structural longevity across environments.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '31px',
    offsetY: '24px',
    scale: 1.25
  },
  {
    id: 'sunken-mule-coral',
    title: 'SUNKEN MULE',
    subtitle: 'DESERT CORAL',
    image: 'https://skylrk.com/cdn/shop/files/SKYLRK_32composite_CORAL.png?v=1774913713&width=800',
    hex: '#e48ea5',
    price: 12000,
    soldOut: false,
    category: 'Footwear',
    description: 'Blush pink organic EVA sculpted clog slide. Sculpted using custom CAD algorithms to optimize pressure dispersion in every heel cycle.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '1px',
    offsetY: '1px',
    scale: 1.25
  },
  {
    id: 'denim-short-light',
    title: 'DENIM SHORT',
    subtitle: 'WASH 3010 LIGHT',
    image: 'https://skylrk.com/cdn/shop/files/SLB021-3010_FRONT.png?v=1774918722&width=800',
    hex: '#90b5cd',
    price: 5800,
    soldOut: false,
    category: 'Joggers',
    description: 'Thick, heavy Japanese cotton slub denim shorts. Heavily washed for extreme softness while maintaining clean industrial vintage structures.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '8px',
    offsetY: '25px',
    scale: 1.0
  },
  {
    id: 'denim-short-dark',
    title: 'DENIM SHORT',
    subtitle: 'WASH 3011 METALLIC',
    image: 'https://skylrk.com/cdn/shop/files/SLB021-3011_FRONT.png?v=1774918725&width=800',
    hex: '#637097',
    price: 5800,
    soldOut: true,
    category: 'Joggers',
    description: 'Industrial dark indigo washed denim cutoff shorts with complex copper rivet details and structural pocket linings. Designed to distress elegantly with wear.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '-22px',
    offsetY: '-1px',
    scale: 1.0
  },
  {
    id: 'pleated-jean-light',
    title: 'PLEATED DENIM JEAN',
    subtitle: 'WASH 3010 LIGHT',
    image: 'https://skylrk.com/cdn/shop/files/SLB018-3010-1.png?v=1768432375&width=800',
    hex: '#90b5cd',
    price: 8900,
    soldOut: false,
    category: 'Joggers',
    description: 'High-waisted, spacious pleated denim trousers in light indigo wash. Distinct dual front pleat folds create an elegant tailored taper that works uniquely with boots.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '15px',
    offsetY: '-27px',
    scale: 1.3
  },
  {
    id: 'pleated-jean-dark',
    title: 'PLEATED DENIM JEAN',
    subtitle: 'WASH 3011 INDIGO',
    image: 'https://skylrk.com/cdn/shop/files/SLB018-3011-1.png?v=1768432375&width=800',
    hex: '#637097',
    price: 8900,
    soldOut: false,
    category: 'Joggers',
    description: 'Structured deep wash tailored jeans with a relaxed drop rise. Dual front architectural details create a structured line framing the lower silhouette.',
    sizeOptions: ['S', 'M', 'L', 'XL', 'XXL'],
    offsetX: '-15px',
    offsetY: '26px',
    scale: 1.3
  },
  {
    id: 'beach-slide-green',
    title: 'BEACH SLIDE',
    subtitle: 'SEABED GREEN',
    image: 'https://skylrk.com/cdn/shop/files/Beach_Slides_035_Right_Green_1500_b11db918-023a-4625-9409-741439bc6e28.png?v=1776832909&width=800',
    hex: '#306e5f',
    price: 3200,
    soldOut: false,
    category: 'Footwear',
    description: 'Plush one-piece molded athletic slide sandals built from waterproof, anti-odor bio-EVA. High cushion footbed ideal for hot sandy walks or poolside leisure.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '22px',
    offsetY: '0px',
    scale: 1.15
  },
  {
    id: 'beach-slide-tennis',
    title: 'BEACH SLIDE',
    subtitle: 'TENNIS LIQUID',
    image: 'https://skylrk.com/cdn/shop/files/SLF003-5002-2_64135e62-7d6e-4abc-804e-ac06460083e4.png?v=1776832930&width=800',
    hex: '#C1D256',
    price: 3200,
    soldOut: false,
    category: 'Footwear',
    description: 'Vibrant fluorescent tennis lime pool slides with premium deep traction grooves. Fits custom snug and offers structural support on wet surfaces.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '-8px',
    offsetY: '-26px',
    scale: 1.15
  },
  {
    id: 'beach-slide-blue',
    title: 'BEACH SLIDE',
    subtitle: 'ROYAL BLUE',
    image: 'https://skylrk.com/cdn/shop/files/Beach_Slide_031_Right_Blue_1500_35b6b02a-e37c-4ca1-b26d-94e94bb3bb5b.png?v=1776833021&width=800',
    hex: '#005BD3',
    price: 3200,
    soldOut: false,
    category: 'Footwear',
    description: 'Cobalt ocean blue molded recreation slides. Extremely light and fully floatable structure built to survive long-term ultraviolet sun exposure.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '29px',
    offsetY: '27px',
    scale: 1.15
  },
  {
    id: 'beach-slide-pink',
    title: 'BEACH SLIDE',
    subtitle: 'FLAMINGO PINK',
    image: 'https://skylrk.com/cdn/shop/files/Beach_Slide_019_Pink_Right_1500_a3b1e3da-4ef8-4517-9d1d-498143066969.png?v=1776832996&width=800',
    hex: '#FFC0CB',
    price: 3200,
    soldOut: false,
    category: 'Footwear',
    description: 'Soft pastelled pink custom pool slides with deep anti-slip foot curves. The perfect high-comfort summer companion for home or beach drops.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '-1px',
    offsetY: '1px',
    scale: 1.15
  },
  {
    id: 'beach-slide-grey',
    title: 'BEACH SLIDE',
    subtitle: 'CONCRETE STRAW',
    image: 'https://skylrk.com/cdn/shop/files/SLF003-1005-2_5cadaa98-95aa-4b64-81b6-73ead168e6a4.png?v=1776833109&width=800',
    hex: '#b4b4b4',
    price: 3200,
    soldOut: false,
    category: 'Footwear',
    description: 'Minimal slate concrete gray slides. Subdued organic pigment coloring fits seamlessly under black, raw, or ecology styled collection garments.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '-31px',
    offsetY: '-25px',
    scale: 1.1
  },
  {
    id: 'beach-slide-seal',
    title: 'BEACH SLIDE',
    subtitle: 'SEAL DARK CHARCOAL',
    image: 'https://skylrk.com/cdn/shop/files/SKYLRK_SEAL_SLIDE_RIGHT_c04c4c2c-d958-482d-96e8-0fef372b7a3c.png?v=1776833305&width=800',
    hex: '#77797E',
    price: 3200,
    soldOut: false,
    category: 'Footwear',
    description: 'Matte dark carbon gray pool slides with complex underfoot active drainage micro-vents. Textured structure grips secure and stays fresh indefinitely.',
    sizeOptions: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10', 'US 11', 'US 12'],
    offsetX: '6px',
    offsetY: '28px',
    scale: 1.1
  }
];

export const WALLPAPERS = [
  {
    id: 'wp-neon-grid',
    title: 'SKYLRK ACID GREEN GRID',
    colorHex: '#D1F362',
    imageUrl: 'https://skylrk.com/cdn/shop/files/GB_v2_1_LIZ.png?v=1776312165&width=800',
    category: 'Desktop'
  },
  {
    id: 'wp-iris-clouds',
    title: 'SKYLRK SILK IRIS CLOUD',
    colorHex: '#c3bfd8',
    imageUrl: 'https://skylrk.com/cdn/shop/files/REVERSEHOODIE_IRIS_FRONT.png?v=1777408516&width=800',
    category: 'Desktop'
  },
  {
    id: 'wp-cyber-case',
    title: 'SKYLRK BUMP RED SPEC',
    colorHex: '#EE4F4F',
    imageUrl: 'https://skylrk.com/cdn/shop/files/IPHONE_17_PRO_JELLY_BACK_29667_1_jpg_64972a29-33ea-4cc4-8b5e-2cbf1a9f219b.png?v=1768581985&width=800',
    category: 'Mobile'
  },
  {
    id: 'wp-sunken-cave',
    title: 'SKYLRK SUNKEN EXTREME',
    colorHex: '#353433',
    imageUrl: 'https://skylrk.com/cdn/shop/files/SKYLRK_32composite_CAVE.png?v=1774913722&width=800',
    category: 'Mobile'
  },
  {
    id: 'wp-beach-slides',
    title: 'SKYLRK OCEAN HORIZONS',
    colorHex: '#005BD3',
    imageUrl: 'https://skylrk.com/cdn/shop/files/Beach_Slide_031_Right_Blue_1500_35b6b02a-e37c-4ca1-b26d-94e94bb3bb5b.png?v=1776833021&width=800',
    category: 'Mobile'
  }
];

export const FAQ_DATA = [
  {
    q: 'WHEN IS THE NEXT DROPS RELEASE?',
    a: 'We drop collections in highly curated seasonal events. Sign up for the internal newsletter or follow us on Instagram (@skylrk) to join the access queue early.'
  },
  {
    q: 'HOW ARE SKYLRK CLOTHING CORES CONSTRUCTED?',
    a: 'All reverse hoodies and joggers are woven from 100% organic cotton loopback French terry ranging from 550GSM to 620GSM. Individual products undergo garfield dye washes to acquire structural vintage textures.'
  },
  {
    q: 'DO YOU OFFER SECURE INTERNATIONAL SHIPPING?',
    a: 'Yes, we integrate with Global-e to ship securely to over 150 countries. Duty taxes and custom tariffs are calculated seamlessly at our Checkout module.'
  },
  {
    q: 'HOW CAN I RETURN A SPECIFIC SIZE OR VARIANT?',
    a: 'We accept returning unworn products inside original custom bags with tags intact within 14 calendar days of your delivery. Reach out in the Contact sheet to receive a prepaid label.'
  }
];

export const POLICY_TABS = {
  faq: {
    title: 'Frequently Asked Questions',
    content: 'Find rapid answers regarding delivery timelines, organic material construction, drop schedules, and sizing configurations.'
  },
  privacy: {
    title: 'Privacy Policy',
    content: 'We prioritize your privacy above all. Personal transaction details are strictly guarded using modern Shopify SSL standards. We do not sell or telemetry your shopping habits to third-party cookies.'
  },
  returns: {
    title: 'Returns & Exchange Terms',
    content: 'Initiate a returns request through our dashboard. Unused items in pristine condition are fully refundable. Please note that custom drops or final sale clothing beanies cannot be refunded.'
  },
  terms: {
    title: 'Terms of Service',
    content: 'By navigating our store, you fully accept purchase terms. Drops are first-come, first-served. Limited quantities available per cart block. Double bookings will automatically trigger a redundant payment void.'
  },
  accessibility: {
    title: 'Accessibility Statement',
    content: 'We actively maintain our online store elements targeting complete conformance with the Web Content Accessibility Guidelines (WCAG 2.1). Enjoy custom dark text states, high-contrast buttons, and logical keyboard navigation loops.'
  }
};